version: "3.9"

services:
  lung-disease-app:
    build: .
    container_name: lung-disease-app
    ports:
      - "8501:8501"
    volumes:
      - ./results:/app/results
      - ./model:/app/model
    environment:
      - GIT_COMMIT=${GIT_COMMIT}
    restart: unless-stopped