version: "3.9"

services:
  lung-disease-app:
    build:
      context: .
      args:
        GIT_COMMIT: ${GIT_COMMIT:-Not available}
    container_name: lung-disease-app
    ports:
      - "8501:8501"
    volumes:
      - ./results:/app/results
      - ./model:/app/model
    restart: unless-stopped